In [102]:
import numpy as np
import pandas as pd
from numpy import *
from matplotlib.image import imread

## DataType & Attribute

In [2]:
#Numpy's main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
#Shape is (1,3) (1 row and 3 columns), we only see 3, initially cuz there's just one row
a1.shape 

(3,)

In [4]:
a2 = np.array ([[1,2.0,3.3],
               [4,5,6.5]])

a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
               
               [[10,11,12],
                [13,14,15],
                [16,17,18]]])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
#Shape is 2 rows and 3 columns
print(a2.shape)
a2

(2, 3)


array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [7]:
#Shape is 2 groups, 3 rows and 3 columns
print(a3.shape)
a3

(2, 3, 3)


array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

### Axis & Dimensions 
Axis = 0  Row |
Axis = 1  Column


In [8]:
a1.ndim,a2.ndim,a3.ndim

(1, 2, 3)

In [9]:
a1.dtype,a2.dtype,a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [10]:
a1.size,a2.size,a3.size

(3, 6, 18)

In [11]:
type(a1),type(a2),type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [12]:
#Create a DataFrame from a NumPy Array
import pandas as pd
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## Creating NumPy Fixed/Random Arrays 

In [13]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [14]:
sample_array.dtype

dtype('int32')

In [15]:
#Parameter is shape,default number is a float
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
#Parameter is shape,default number is a float
zeros =np.zeros((3,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
#Parameter is start,max and interval
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [18]:
#Parameter is min,exclusive max and size
random_array = np.random.randint(0,10,size =(3,5))
random_array

array([[7, 5, 6, 1, 6],
       [6, 5, 5, 8, 1],
       [8, 0, 1, 4, 5]])

In [19]:
#Random floats from 0-10
random_array_2 = np.random.random((5,3))
random_array_2  

array([[0.72277529, 0.40830214, 0.27572421],
       [0.15664993, 0.27984427, 0.97785942],
       [0.3996726 , 0.91842865, 0.129274  ],
       [0.49235378, 0.23573631, 0.39423339],
       [0.39379614, 0.48200293, 0.90587283]])

In [20]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.4228966 , 0.8582433 , 0.65396822],
       [0.67264467, 0.83460524, 0.6279335 ],
       [0.43451298, 0.27906053, 0.43201686],
       [0.12620276, 0.4540942 , 0.1309991 ],
       [0.45957446, 0.00722655, 0.7426599 ]])

In [21]:
#Pseudo-random numbers
#Allows a constant randomization seed since we set it on a certain number
np.random.seed(seed =0)
random_array_4 = np.random.randint(10,size =(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

## Viewing Arrays and Matrices

In [22]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
a1

array([1, 2, 3])

In [24]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [25]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [26]:
#Indexing according to second and last index of the shape ()
a1[0]

1

In [27]:
a1.shape

(3,)

In [28]:
a2[0]

array([1. , 2. , 3.3])

In [29]:
a2.shape

(2, 3)

In [30]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
a3.shape

(2, 3, 3)

In [32]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [33]:
#2 groups of 3 with 4 rows and 5 columns
a4 = np.random.randint(10,size=(2,3,4,5))
a4

array([[[[6, 7, 7, 8, 1],
         [5, 9, 8, 9, 4],
         [3, 0, 3, 5, 0],
         [2, 3, 8, 1, 3]],

        [[3, 3, 7, 0, 1],
         [9, 9, 0, 4, 7],
         [3, 2, 7, 2, 0],
         [0, 4, 5, 5, 6]],

        [[8, 4, 1, 4, 9],
         [8, 1, 1, 7, 9],
         [9, 3, 6, 7, 2],
         [0, 3, 5, 9, 4]]],


       [[[4, 6, 4, 4, 3],
         [4, 4, 8, 4, 3],
         [7, 5, 5, 0, 1],
         [5, 9, 3, 0, 5]],

        [[0, 1, 2, 4, 2],
         [0, 3, 2, 0, 7],
         [5, 9, 0, 2, 7],
         [2, 9, 2, 3, 3]],

        [[2, 3, 4, 1, 2],
         [9, 1, 4, 6, 8],
         [2, 3, 0, 0, 6],
         [0, 6, 3, 3, 8]]]])

In [34]:
#Get the 4 column numbers
a4[:,:,:,:4]

array([[[[6, 7, 7, 8],
         [5, 9, 8, 9],
         [3, 0, 3, 5],
         [2, 3, 8, 1]],

        [[3, 3, 7, 0],
         [9, 9, 0, 4],
         [3, 2, 7, 2],
         [0, 4, 5, 5]],

        [[8, 4, 1, 4],
         [8, 1, 1, 7],
         [9, 3, 6, 7],
         [0, 3, 5, 9]]],


       [[[4, 6, 4, 4],
         [4, 4, 8, 4],
         [7, 5, 5, 0],
         [5, 9, 3, 0]],

        [[0, 1, 2, 4],
         [0, 3, 2, 0],
         [5, 9, 0, 2],
         [2, 9, 2, 3]],

        [[2, 3, 4, 1],
         [9, 1, 4, 6],
         [2, 3, 0, 0],
         [0, 6, 3, 3]]]])

In [35]:
#Get 4,6,4,4,3
#Do it one by one so it's simpler
# From the 1 index group, first group, first row and until 5 numbers
a4[1,0,0,:5]

array([4, 6, 4, 4, 3])

## Manipulating & Comparing Arrays

### Arithmetic

In [36]:
a1

array([1, 2, 3])

In [37]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [38]:
a1 + ones
np.add(a1,ones)

array([2., 3., 4.])

In [39]:
a1-ones

array([0., 1., 2.])

In [40]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [41]:
#It multiplies per column
a1*a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [42]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [43]:
#Floor division removes the decimals
a2//a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [44]:
a2/a1

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [45]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [46]:
a2**2
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

### Aggregation

In [47]:
np.sum(a2)

21.8

In [48]:
massive_array = np.random.random(100000)
massive_array

array([0.16494046, 0.36980809, 0.14644176, ..., 0.55947553, 0.62297663,
       0.05077999])

In [49]:
#Np.sum is 526 times faster
%timeit sum(massive_array)
%timeit np.sum(massive_array)

33.1 µs ± 618 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
35 µs ± 2.74 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [50]:
np.mean(a2)

3.6333333333333333

In [51]:
np.min(a2)

1.0

In [52]:
np.max(a2)

6.5

In [53]:
#standard deviation = a measure of how spread out the number is from the mean
np.std(a2)

1.8226964152656422

In [54]:
# Variance = measure of average degree to which number is different from the mean
# Higher variance = wider range of numbers
# lower variance = lower range of numbers
np.var(a2)

3.3222222222222224

## Reshaping and Transposing
Machine learning takes in aligned inputs in order to expect correct output so we need to change the dimensions/shape of the series/array

In [55]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [56]:
a2.shape

(2, 3)

In [57]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [58]:
a3.shape

(2, 3, 3)

### Reshaping

In [59]:
# a2*a3 cannot be multiplied because two dimensions have to be compatible: they are equal or one of them is 1
a2_reshaped = a2.reshape(2,3,1)
a2_reshaped

array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.5]]])

In [60]:
# a2_reshaped can now be multiplied since the a2 can be evenly distributed to a3 based on its new dimension
a2_reshaped*a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 23.1,  26.4,  29.7]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [104. , 110.5, 117. ]]])

### Transposing
Swaps the axises around

In [61]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [62]:
a2.shape

(2, 3)

In [63]:
a2.T

array([[1. , 4. ],
       [2. , 5. ],
       [3.3, 6.5]])

In [64]:
a2.T.shape

(3, 2)

In [65]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [66]:
a3.shape

(2, 3, 3)

In [67]:
a3.T.shape

(3, 3, 2)

In [68]:
a3.T

array([[[ 1, 10],
        [ 4, 13],
        [ 7, 16]],

       [[ 2, 11],
        [ 5, 14],
        [ 8, 17]],

       [[ 3, 12],
        [ 6, 15],
        [ 9, 18]]])

## Dot Product



In [69]:
np.random.seed(0)

mat1 = np.random.randint(10,size=(5,3))
mat2 = np.random.randint(10,size=(5,3))

In [70]:
mat1    

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [71]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [72]:
#Element Wise multiplication (hadamard product)
mat1*mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [73]:
### mat1 * mat2 cannot be multiplied

In [74]:
#Transpose mat2 so we can match the inner dimensions
mat1.shape,mat2.T.shape


((5, 3), (3, 5))

In [75]:
#Dot product, top row is multiplied by the each column and adding up the total (top * column 1, top * column 2 , middle * column 1, middle * column 2)
#Number inside must match!!! We can use TRANSPOSE FOR THIS
#The result will be the number of number of rows of the bigger one and number of columns of the bigger one

mat3=np.dot(mat1,mat2.T)
mat3

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

### Dot Product Example

In [76]:
np.random.seed(0)
#Number of jars sold
sales_amounts = np.random.randint(20,size=(5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [77]:
#Create a weekly DF
weekly_sales = pd.DataFrame(sales_amounts,
                            index =["Mon","Tues","Wed","Thurs","Fri"],
                            columns =["Almond butter","Peanut Butter","Cashew Butter"])
weekly_sales

Almond butter  Peanut Butter  Cashew Butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [78]:
prices = np.array([10,8,12])
prices  

array([10,  8, 12])

In [79]:
prices.shape

(3,)

In [80]:
#Reshape prices since pandas is expecting a different format for shape since NP doesnt indicate (1,3) for 1 row
product_prices = pd.DataFrame(prices.reshape(1,3),
                              index = ["Price"],
                              columns = ["Almond butter","Peanut Butter","Cashew Butter"])
product_prices

Almond butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [81]:
weekly_sales.shape

(5, 3)

In [82]:
prices.shape

(3,)

In [83]:
dot_product = np.dot(weekly_sales,prices.T)
dot_product

array([240, 138, 458, 232, 142])

In [84]:
product_prices

Almond butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [85]:
weekly_sales["Total"] = dot_product
weekly_sales

Almond butter  Peanut Butter  Cashew Butter  Total
Mon               12             15              0    240
Tues               3              3              7    138
Wed                9             19             18    458
Thurs              4              6             12    232
Fri                1              6              7    142

## Comparison Operators

In [86]:
a1

array([1, 2, 3])

In [87]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [88]:
bool_array = a1>=a2
bool_array

array([[ True,  True, False],
       [False, False, False]])

In [89]:
type(bool_array),bool_array.dtype

(numpy.ndarray, dtype('bool'))

In [90]:
a1 == a2

array([[ True,  True, False],
       [False, False, False]])

## Sorting Arrays

In [91]:
random.seed(0)
random_array = np.random.randint(10,size=(3,5))
random_array

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1]])

In [92]:
np.sort(random_array)

array([[0, 3, 3, 5, 7],
       [2, 3, 4, 5, 9],
       [1, 6, 7, 8, 8]])

In [93]:
random_array

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1]])

In [94]:
#Sorts the indices of the array per row (0 being the lowest, 4 being the highest since there are 5 columns)
# [1]:0,[2]:3,[3]:3,[0]:5,[4]:7
np.argsort(random_array)

array([[1, 2, 3, 0, 4],
       [3, 1, 4, 2, 0],
       [4, 1, 0, 2, 3]], dtype=int64)

In [95]:
random_array

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1]])

In [96]:
#Per column, axis 0 means row so going down vertically
np.argmax(random_array,axis=0)

array([1, 2, 2, 2, 0], dtype=int64)

In [97]:
#Per row, axis 1 means column so going right horizontally
np.argmax(random_array,axis=1)

array([4, 0, 2], dtype=int64)

In [98]:
np.argmin(a1)

0

In [99]:
np.argmax(a1)

2

## Practical Example - NumPy in Action!!!

<img src="panda.png">


In [104]:
# Turn image into NumPy Array
# Pixels -> color values -> stored in an array
panda = imread("panda.png")
print(type(panda))

<class 'numpy.ndarray'>


In [105]:
panda.size,panda.shape,panda.ndim

(823854, (394, 697, 3), 3)

In [111]:
panda[:2]

array([[[0.05490196, 0.05490196, 0.05490196],
        [0.05490196, 0.05490196, 0.05490196],
        [0.05490196, 0.05490196, 0.05490196],
        ...,
        [0.05490196, 0.05490196, 0.05490196],
        [0.05490196, 0.05490196, 0.05490196],
        [0.05490196, 0.05490196, 0.05490196]],

       [[0.05490196, 0.11372549, 0.07450981],
        [0.05490196, 0.11372549, 0.07450981],
        [0.05490196, 0.11372549, 0.07450981],
        ...,
        [0.16470589, 0.13725491, 0.09411765],
        [0.16470589, 0.13725491, 0.09019608],
        [0.16470589, 0.13725491, 0.08627451]]], dtype=float32)